from pathlib import Path
from typing import Protocol


class TrainingBackend(Protocol):
    def snapshot(self): ...
    def restore(self, snapshot): ...
    def state_hash(self) -> str: ...
    def generate(self, prompt, max_new_tokens, seed=0, temperature=0.0) -> str: ...
    def train(self, corrections, seed, max_steps=None, log_path=None) -> dict: ...
    def measure_loss(self, examples) -> float: ...
    def save_checkpoint(self, path: Path, metadata: dict): ...
    def load_checkpoint(self, path: Path): ...
